"""add relationships

Revision ID: 4637f2d5ee05
Revises: 55aaea1aedce
Create Date: 2025-01-18 14:37:11.198185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4637f2d5ee05'
down_revision = '55aaea1aedce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_title', sa.String(), nullable=True),
    sa.Column('review_body', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cookie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cookie_id'], ['cookies.id'], name=op.f('fk_reviews_cookie_id_cookies')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
