"""add images

Revision ID: 55aaea1aedce
Revises: 9264d5f7ec27
Create Date: 2025-01-18 14:14:19.380947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55aaea1aedce'
down_revision = '9264d5f7ec27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cookies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cookies', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
