"""add images and frosting to cookies

Revision ID: 9264d5f7ec27
Revises: 525521495833
Create Date: 2025-01-18 14:12:27.589026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9264d5f7ec27'
down_revision = '525521495833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cookies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frosting', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cookies', schema=None) as batch_op:
        batch_op.drop_column('frosting')

    # ### end Alembic commands ###
